import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

@table('users')
export class User {

  constructor(obj = {}) {
    for (const key in obj) {
      this[key] = obj[key];
    }
  }

  @autoGeneratedHashKey()
  public id: string;

  @attribute()
  public username: string;

  @attribute()
  public email: string;

}
